---
title: "Kino _Green_Space"
author: "Kino Watanabe"
date: "2025-11-13"
output: html_document
---

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(tigris)

```

```{r}
parks_df =
  read_csv("Data Folder/Parks_Properties_Oct2025.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(acquisitiondate, borough, zipcode, address, 
         eapply, location, acres, typecategory, retired)

shooting25_df =
  read_csv("Data Folder/Shooting_2025.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |> 
  distinct(incident_key, .keep_all = TRUE) |> 
  filter(boro == "MANHATTAN")


shooting06_24_df = 
  read_csv("Data Folder/Shooting_Historic.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |> 
    distinct(incident_key, .keep_all = TRUE) |> 
     filter(boro == "MANHATTAN")

```


```{r}

```

```{r}
library(tidygeocoder)
# 1. Geocode using census
parks_geo <- parks_df |>
  geocode(address, method = "census", lat = lat, long = lon)

parks_geo_clean <- parks_geo |>
  filter(!is.na(lat) & !is.na(lon))

parks_sf <- st_as_sf(parks_geo_clean,
                     coords = c("lon", "lat"),
                     crs = 4326)
# 2. Convert to sf
parks_sf <- st_as_sf(parks_geo, coords = c("lon", "lat"), crs = 4326)

# 3. Load Census tracts (example: NY)
tracts <- tracts("NY", year = 2023, class = "sf")

# 4. Spatial join to get GEOID
parks_with_geoid <- st_join(parks_sf, tracts[, c("GEOID")])
```
 
```{r}

nyc_counties <- c("061", "005", "081", "047", "085") # NY, Bronx, Queens, Kings, Richmond
total_pop_var <- "B01003_001" # Total Population (Estimate)

# 4. Download Total Population Data with Geometry
nyc_pop_data <- get_acs(
  geography = "tract",
  variables = total_pop_var,
  state = "NY",
  county = nyc_counties,
  geometry = TRUE,
  year = 2023 # Use a recent ACS 5-year estimate
)

# 5. Create the Interactive Map
# zcol specifies the column to shade the map by (the estimate for total population)
mapview(
  nyc_pop_data, 
  zcol = "estimate", 
  legend = TRUE, 
  layer.name = "Total Population (ACS Est.)",
  map.types = "CartoDB.Positron" # A clean, simple background map
)

```

