---
title: "Murder flag"
author: "Miho Kawanami"
date: "2025-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(mapview)
```

```{r}
census_api_key("71edc420ec0b86cf5a54c3fc72727f4149467e79")
```

```{r}
library(tidyverse)
dat1 = read.csv("./Data Folder/Shooting_Historic.csv")
dat2 = read.csv("./Data Folder/Shooting_2025.csv")

dat1 = dat1 |>
  mutate(STATISTICAL_MURDER_FLAG = STATISTICAL_MURDER_FLAG %in% c(TRUE, "true", "True"))

dat2 = dat2 |>
  mutate(STATISTICAL_MURDER_FLAG = STATISTICAL_MURDER_FLAG %in% c(TRUE, "true", "True"))

dat_all = bind_rows(
dat1 |> mutate(source = "historic"),
dat2 |> mutate(source = "y2025")
)
```

## By Each Borough_historic
```{r}
dat1_boro = dat1 |>
  group_by(BORO) |>
  summarise(
    n_murder = sum(STATISTICAL_MURDER_FLAG),  
    n_total = n(),                             
    prop_murder = n_murder / n_total,
    .groups = "drop"
  )

dat1_boro
```

## By Each Borough_all
```{r boro-prop, message=FALSE, warning=FALSE}
dat_all_boro_prop = dat_all |>
  group_by(BORO) |>
  summarise(
    n_murder = sum(STATISTICAL_MURDER_FLAG),
    n_total  = n(),
    prop_murder = n_murder / n_total,
    .groups = "drop"
  )

dat_all_boro_prop
```

```{r boro-count, message=FALSE, warning=FALSE}
dat_all_boro_count = dat_all |>
  group_by(BORO) |>
  summarise(
    n_murder = sum(STATISTICAL_MURDER_FLAG),
    n_total  = n(),
    .groups = "drop"
  )

dat_all_boro_count
```

```{r boro-map-data, message=FALSE, warning=FALSE}
nyc_boro = tigris::counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond"))

boro_to_county = function(df) {
  df |>
    mutate(
      county_name = case_when(
        BORO == "MANHATTAN"     ~ "New York",
        BORO == "BROOKLYN"      ~ "Kings",
        BORO == "BRONX"         ~ "Bronx",
        BORO == "QUEENS"        ~ "Queens",
        BORO == "STATEN ISLAND" ~ "Richmond"
      )
    )
}

dat_all_boro_prop = boro_to_county(dat_all_boro_prop)
dat_all_boro_count = boro_to_county(dat_all_boro_count)

```

## Map_ percentage__historic

```{r message=FALSE, warning=FALSE}
nyc_boro = tigris::counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond"))

dat1_boro = dat1_boro |>
  mutate(
    county_name = case_when(
      BORO == "MANHATTAN" ~ "New York",
      BORO == "BROOKLYN" ~ "Kings",
      BORO == "BRONX" ~ "Bronx",
      BORO == "QUEENS" ~ "Queens",
      BORO == "STATEN ISLAND" ~ "Richmond"
    )
  )

nyc_boro_map = nyc_boro |>
  left_join(dat1_boro, by = c("NAME" = "county_name"))

mapview(nyc_boro_map,
        zcol = "prop_murder",
        layer.name = "Proportion of Murder by Borough",
        popup = paste0("Borough: ", nyc_boro_map$BORO,
                       "<br>Murder proportion: ",
                       round(nyc_boro_map$prop_murder, 3)))
```

## map (percentage)_all
```{r map-percentage, message=FALSE, warning=FALSE}
nyc_boro_map_prop = nyc_boro |>
  left_join(dat_all_boro_prop, by = c("NAME" = "county_name"))

mapview(
  nyc_boro_map_prop,
  zcol = "prop_murder",
  layer.name = "Proportion of Murder by Borough (all years)",
  popup = paste0(
    "Borough: ", nyc_boro_map_prop$BORO, "<br>",
    "Murder proportion: ", round(nyc_boro_map_prop$prop_murder, 3), "<br>",
    "Total shootings: ", nyc_boro_map_prop$n_total
  )
)
```

## map (count)_historic

```{r}
dat1_boro = dat1 |>
  group_by(BORO) |>
  summarise(
    n_murder = sum(STATISTICAL_MURDER_FLAG),
    n_total  = n(),
    .groups = "drop"
  )


dat1_boro <- dat1_boro |>
  mutate(
    COUNTY = case_when(
      BORO == "MANHATTAN" ~ "New York",
      BORO == "BROOKLYN" ~ "Kings",
      BORO == "BRONX" ~ "Bronx",
      BORO == "QUEENS" ~ "Queens",
      BORO == "STATEN ISLAND" ~ "Richmond"
    )
  )

library(tigris)
options(tigris_progress = FALSE, tigris_use_cache = TRUE)

nyc_boro_map <- counties(state = "NY", cb = TRUE) |>
  filter(NAME %in% c("Bronx", "Kings", "New York", "Queens", "Richmond"))

nyc_boro_map <- nyc_boro_map |>
  left_join(dat1_boro, by = c("NAME" = "COUNTY"))

mapview(
  nyc_boro_map,
  zcol = "n_murder",
  layer.name = "Number of Murder Cases by Borough",
  popup = paste0(
    "Borough: ", nyc_boro_map$BORO, "<br>",
    "Number of murder cases: ", nyc_boro_map$n_murder, "<br>",
    "Total shootings: ", nyc_boro_map$n_total
  )
)
```

## map (count)_all
```{r map-count, message=FALSE, warning=FALSE}
nyc_boro_map_count = nyc_boro |>
  left_join(dat_all_boro_count, by = c("NAME" = "county_name"))

mapview(
  nyc_boro_map_count,
  zcol = "n_murder",
  layer.name = "Number of Murder Cases by Borough (all years)",
  popup = paste0(
    "Borough: ", nyc_boro_map_count$BORO, "<br>",
    "Number of murder cases: ", nyc_boro_map_count$n_murder, "<br>",
    "Total shootings: ", nyc_boro_map_count$n_total
  )
)
```

## regression model 
```{r regression, message=FALSE, warning=FALSE}
dat_all_stable = dat_all |>
  filter(VIC_SEX %in% c("M","F")) |>                 
  filter(!VIC_AGE_GROUP %in% c("UNKNOWN", "", NA)) |>
  mutate(
    age_simple = case_when(
      VIC_AGE_GROUP %in% c("<18", "18-24") ~ "young",
      VIC_AGE_GROUP %in% c("25-44", "45-64") ~ "adult",
      VIC_AGE_GROUP == "65+" ~ "old"
    ),
    age_simple = factor(age_simple, levels = c("adult", "young", "old")),
    STATISTICAL_MURDER_FLAG = as.numeric(STATISTICAL_MURDER_FLAG),
    VIC_SEX = factor(VIC_SEX)
  )

fit_stable = glm(
  STATISTICAL_MURDER_FLAG ~ VIC_SEX + age_simple,
  data = dat_all_stable,
  family = binomial()
)

summary(fit_stable)

```

## OR
```{r}
library(broom)
tidy(fit_stable, exponentiate = TRUE, conf.int = TRUE)
```



